### PR TITLE
Build electron on travis CI

### PR DESCRIPTION
**Pull request by lexoyo**

### CODE REVIEW

**Comment by lexoyo** [comment]
@JbIPS can I merge this?

**Comment by JbIPS** [comment]
Only if you squash it 😃

**Comment by lexoyo** [comment]
@JbIPS it looks like the linters actually build silex every time, the should only check the code right?

**Comment by JbIPS** [comment]
Yeah I'm looking for a way to skip the installation step.

Maybe something with `install: skip`

**Pull request merged**
