### PR TITLE
Handle the right click

### PR DESCRIPTION
**Pull request by tariqbenezza**
Too many people using Silex tried to right click on the workspace.

I propose to help them by handle this right click and display a message :

image

Tell me if it's Ok for you ?

Thank you in advance

### CODE REVIEW

**Comment by tariqbenezza** [comment]
I'm on it !

**Comment by lexoyo** [comment]
I have removed all my commits from your branch and created a new branch here
https://github.com/silexlabs/Silex/tree/RightClick

Please reset your branch to replace it with mine with 
```
$ git remote add upstream https://github.com/silexlabs/Silex.git
$ git fetch upstream
$ git reset --hard upstream/RightClick
```

**Comment by tariqbenezza** [comment]
All the changes required are done
Please advise @lexoyo

**Comment by RayPylant** [comment]
hope these things get worked out cause messed me up my pc, had to reload my pc. Good thing i made 2 copies of my system and files.

**Pull request closed without merging**
