### PR TITLE
HTML attributes editor

### PR DESCRIPTION
**Pull request by lexoyo**
Todo before merge

* [x] add HTML attributes to the model
* [x] UI
* [x] html attributes are an array of strings, but when you enter `data-test="b"` it creates in the DOM the attribute `data-test=""b""` => [need to handle quotes and double quotes here](https://github.com/lexoyo/Silex/blob/html-attr/src/ts/client/element-store/observer.ts#L140)

When you need to add HTML attributes to the selected element(s), you can write them to this field

HTML attributes

For example it can be useful to set an HTML ID (for anchors or else), Aria accessibility attributes, ...

### CODE REVIEW

**Comment by lexoyo** [comment]
hi
I started to implement this option, it is here and if i remember correctly it is working
https://github.com/silexlabs/Silex/pull/1105

**Comment by aallnneess** [comment]
Hm, but ive no "Element" option....just CSS...

image

**Comment by lexoyo** [comment]
could you give it a try? are you familiar with github?

**Comment by aallnneess** [comment]
` are you familiar with github?`
not so much..... :-|

**Comment by lexoyo** [comment]
oh ok
I don't understand what you mean, I'll check apache wicket out

**Comment by lexoyo** [comment]
ok i think i see

you want to add elements attributes such as data-*

this is exactly what this PR adds

**Comment by aallnneess** [comment]
okay, thanks. i look deaper how this pull requests work.

thanks

**Comment by lexoyo** [comment]
i am interested in this use case, if i can help in any way please let me know

I have created tools to use silex as a template editor for jekyll and 11ty
this is not announced on silex site yet nor documented but I use it in production already (belighted.com lescousettesdezoe.fr ...)

https://github.com/lexoyo/stastic-designer

**Comment by lexoyo** [comment]
This is quite simple actually

You should clone the repo to your local computer (`git clone https://github.com/silexlabs/Silex.git`), pull my code (`git pull https://github.com/lexoyo/Silex.git html-attr`), then follow the instructions here (`npm install && npm start`)
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-linux-or-macos-or-cloud9

You should have silex running on http://localhost:6805/

**Comment by aallnneess** [comment]
image

pull code is wrong :-|

**Comment by aallnneess** [comment]
image

:-|

**Comment by lexoyo** [comment]
ok, on windows you need to use powershell

it is possible with docker (`docker build .`) but it may be better with 
just npm (`npm install && npm start`)

**Comment by lexoyo** [comment]
did you do this to start docker ?

```
$ docker build -t silex-image .
$ docker run -p 6805:6805 -t silex-image

```

this is how you build the image from source and start it

the other method loads the official image from docker hub

**Comment by lexoyo** [comment]
also please check that your current branch is html-attr

also check that you have the changes

**Comment by aallnneess** [comment]
hey, yes i did it this way. Without the pull it runs nice, but with the pull -> always:

`executor failed running [/bin/sh -c npm run build]: exit code: 1`

`src/ts/server/utils/BackwardCompatV2.5.60.ts(125,3): error TS2741: Property 'attr' is missing in type '{ id: string; pageNames: string[]; classList: string[]; tagName: string; type: ElementType.CONTAINER | ElementType; isSectionContent: boolean; title: string; alt: string; children: string[]; ... 10 more ...; innerHtml: string; }' but required in type 'ElementData'.`

```
#10 44.67 npm ERR! code ELIFECYCLE
#10 44.67 npm ERR! errno 2
#10 44.68 npm ERR! silex-website-builder@2.7.14 build:server:release: `tsc -p tsconfig-server-release.json`
#10 44.68 npm ERR! Exit status 2
#10 44.68 npm ERR!
#10 44.68 npm ERR! Failed at the silex-website-builder@2.7.14 build:server:release script.
#10 44.68 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#10 44.70
#10 44.70 npm ERR! A complete log of this run can be found in:
#10 44.70 npm ERR!     /root/.npm/_logs/2021-05-29T08_57_41_597Z-debug.log
#10 44.70 ERROR: "build:server:release" exited with 2.
#10 44.72 npm ERR! code ELIFECYCLE
#10 44.72 npm ERR! errno 1
#10 44.72 npm ERR! silex-website-builder@2.7.14 build: `run-s cleanup build:css:release build:html build:prodotype build:client:release build:server:release build:monaco-editor`
#10 44.72 npm ERR! Exit status 1
#10 44.72 npm ERR!
#10 44.73 npm ERR! Failed at the silex-website-builder@2.7.14 build script.
#10 44.73 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

but i dont want to waste your time anymore.
thanks

**Comment by aallnneess** [comment]
```
 => ERROR [6/6] RUN npm run build                                                                                 56.4s
------
 > [6/6] RUN npm run build:
#9 0.928
#9 0.928 > silex-website-builder@2.7.14 build /silex
#9 0.928 > run-s cleanup build:css:release build:html build:prodotype build:client:release build:server:release build:monaco-editor
#9 0.928
#9 1.533
#9 1.533 > silex-website-builder@2.7.14 cleanup /silex
#9 1.533 > mkdirp tmp && mv dist/public tmp/ && rm -rf dist && mv tmp dist
#9 1.533
#9 2.223
#9 2.223 > silex-website-builder@2.7.14 build:css:release /silex
#9 2.223 > lessc src/css/_styles.less dist/html/css/admin.css
#9 2.223
#9 3.120
#9 3.120 > silex-website-builder@2.7.14 build:html /silex
#9 3.120 > pug src/html/index.jade --out dist/html/ --no-debug
#9 3.120
#9 3.533
#9 3.562 src/html/index.jade, line 40:
#9 3.562 The .jade extension is deprecated, use .pug for "./templates/includes.jade".
#9 3.562 src/html/index.jade, line 43:
#9 3.562 The .jade extension is deprecated, use .pug for "./templates/workspace.jade".
#9 3.584 src/html/templates/workspace.jade, line 10:
#9 3.584 The .jade extension is deprecated, use .pug for "./menu.jade".
#9 3.584 src/html/templates/workspace.jade, line 18:
#9 3.584 The .jade extension is deprecated, use .pug for "./property-tool.jade".
#9 3.584 src/html/templates/workspace.jade, line 34:
#9 3.584 The .jade extension is deprecated, use .pug for "./settings-dialog.jade".
#9 3.584 src/html/templates/workspace.jade, line 38:
#9 3.584 The .jade extension is deprecated, use .pug for "./dashboard.jade".
#9 3.584 src/html/templates/workspace.jade, line 42:
#9 3.584 The .jade extension is deprecated, use .pug for "./text-format-bar.jade".
#9 3.632 src/html/templates/menu.jade, line 147:
#9 3.632 The .jade extension is deprecated, use .pug for "./page-tool.jade".
#9 4.048   rendered /silex/dist/html/index.html
#9 4.472
#9 4.472 > silex-website-builder@2.7.14 build:prodotype /silex
#9 4.472 > run-s build:folders build:components build:styles
#9 4.472
#9 5.115
#9 5.115 > silex-website-builder@2.7.14 build:folders /silex
#9 5.115 > mkdirp dist/prodotype/components dist/prodotype/styles
#9 5.115
#9 5.547
#9 5.547 > silex-website-builder@2.7.14 build:components /silex
#9 5.547 > prodotype src/prodotype/components dist/prodotype/components/
#9 5.547
#9 5.660 Building /silex/src/prodotype/components to /silex/dist/prodotype/components in current dir: /silex
#9 5.666 Building template aligned-container
#9 5.675 Building template animated-container
#9 5.680 Building template autosize-section
#9 5.681 Building template form
#9 5.684 Building template full-width
#9 5.685 Building template hamburger
#9 5.688 Building template hero-center
#9 5.691 Building template hero-scroll-bottom
#9 5.692 Building template hero-section
#9 5.694 Building template json-box
#9 5.700 Building template map
#9 5.703 Building template share
#9 5.705 Building template skill-bars
#9 5.708 Building template slideshow
#9 5.713 writing /silex/dist/prodotype/components/components.json
#9 6.105
#9 6.105 > silex-website-builder@2.7.14 build:styles /silex
#9 6.105 > prodotype src/prodotype/styles dist/prodotype/styles/
#9 6.105
#9 6.225 Building /silex/src/prodotype/styles to /silex/dist/prodotype/styles in current dir: /silex
#9 6.229 Building template text
#9 6.258 writing /silex/dist/prodotype/styles/components.json
#9 6.619
#9 6.619 > silex-website-builder@2.7.14 build:client:release /silex
#9 6.619 > webpack --config webpack.config.js
#9 6.619
#9 44.77 asset main.js 2.23 MiB [emitted] [minimized] [big] (name: main) 1 related asset
#9 44.77 orphan modules 833 KiB [orphan] 122 modules
#9 44.77 runtime modules 1.46 KiB 6 modules
#9 44.77 cacheable modules 1000 KiB
#9 44.77   modules by path ./node_modules/simplebar/node_modules/core-js/internals/*.js 75.8 KiB 102 modules
#9 44.77   modules by path ./node_modules/simplebar/node_modules/core-js/modules/*.js 17.5 KiB 15 modules
#9 44.77   modules by path ./node_modules/redux-undo/lib/*.js 20.7 KiB
#9 44.77     ./node_modules/redux-undo/lib/index.js 1.63 KiB [built] [code generated]
#9 44.77     ./node_modules/redux-undo/lib/actions.js 1.08 KiB [built] [code generated]
#9 44.77     ./node_modules/redux-undo/lib/helpers.js 2.45 KiB [built] [code generated]
#9 44.77     ./node_modules/redux-undo/lib/reducer.js 11.8 KiB [built] [code generated]
#9 44.77     ./node_modules/redux-undo/lib/debug.js 3.71 KiB [built] [code generated]
#9 44.77   8 modules
#9 44.77
#9 44.77 WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
#9 44.77 This can impact web performance.
#9 44.77 Assets:
#9 44.77   main.js (2.23 MiB)
#9 44.77
#9 44.77 WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
#9 44.77 Entrypoints:
#9 44.77   main (2.23 MiB)
#9 44.77       main.js
#9 44.77
#9 44.77 WARNING in webpack performance recommendations:
#9 44.77 You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
#9 44.77 For more info visit https://webpack.js.org/guides/code-splitting/
#9 44.77
#9 44.77 webpack 5.13.0 compiled with 3 warnings in 36816 ms
#9 45.27
#9 45.27 > silex-website-builder@2.7.14 build:server:release /silex
#9 45.27 > tsc -p tsconfig-server-release.json
#9 45.27
#9 56.21 src/ts/server/utils/BackwardCompatV2.5.60.ts(125,3): error TS2741: Property 'attr' is missing in type '{ id: string; pageNames: string[]; classList: string[]; tagName: string; type: ElementType.CONTAINER | ElementType; isSectionContent: boolean; title: string; alt: string; children: string[]; ... 10 more ...; innerHtml: string; }' but required in type 'ElementData'.
#9 56.23 npm ERR! code ELIFECYCLE
#9 56.23 npm ERR! errno 2
#9 56.24 npm ERR! silex-website-builder@2.7.14 build:server:release: `tsc -p tsconfig-server-release.json`
#9 56.24 npm ERR! Exit status 2
#9 56.24 npm ERR!
#9 56.24 npm ERR! Failed at the silex-website-builder@2.7.14 build:server:release script.
#9 56.24 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 56.27
#9 56.27 npm ERR! A complete log of this run can be found in:
#9 56.27 npm ERR!     /root/.npm/_logs/2021-05-29T11_23_00_370Z-debug.log
#9 56.27 ERROR: "build:server:release" exited with 2.
#9 56.28 npm ERR! code ELIFECYCLE
#9 56.28 npm ERR! errno 1
#9 56.28 npm ERR! silex-website-builder@2.7.14 build: `run-s cleanup build:css:release build:html build:prodotype build:client:release build:server:release build:monaco-editor`
#9 56.28 npm ERR! Exit status 1
#9 56.28 npm ERR!
#9 56.29 npm ERR! Failed at the silex-website-builder@2.7.14 build script.
#9 56.29 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 56.29
#9 56.29 npm ERR! A complete log of this run can be found in:
#9 56.29 npm ERR!     /root/.npm/_logs/2021-05-29T11_23_00_418Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
```

**Comment by lexoyo** [comment]
oh ok
sorry about that
it looks like there is a type error
I'll fix it soon

**Comment by aallnneess** [comment]
That would be really nice, because Silex is my favorite editor - I just need this one function ... :D

**Comment by aallnneess** [comment]
thanks !

**Comment by lexoyo** [comment]
@aallnneess I fixed this issue, please test again and let me know how it goes?

If you have time feel free to document the use of this feature here (I documented a little already)
https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#html-attributes

Have fun!

**Comment by aallnneess** [comment]
> If you have time feel free to document the use of this feature here (I documented a little already)
> https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#html-attributes

I need some time to "train" and checkout with a real world project all the settings....then i can shure edit doku....maybe some youtube videos...

**Comment by aallnneess** [comment]
Html attributes works fine, but CSS Class entry dont work anymore...

cssfehler

**Comment by aallnneess** [comment]
Any Idea ?

**Comment by aallnneess** [comment]
hey, sry. Dont no why, but know it is working.....

**Comment by aallnneess** [comment]
very strange....CSS works know, but there are troubles with the Html attributes....they are thrown together:

miigg

**Comment by lexoyo** [comment]
hello
this is because I expected valid attributes, see the regexp here
https://github.com/silexlabs/Silex/pull/1105/files#diff-7f5219aa9daa4c5017f56cbaefd882df80c70e0d3d2761fb6b6d08a4b45abc64R141

what do you require to be a valid attribute? should I add `:` ? what else?

**Comment by aallnneess** [comment]
hello and thanks for your answer :-)

For wicket i need only the `:` :

`wicket:id="attributeName"`

image

So the IDE can identify that there is a wicket id inside the html tag.

thanks

**Comment by lexoyo** [comment]
in that case we need to add : to the regexp

I will do that as soon as I have time

you can make the change too, and create a pull request

**Comment by lexoyo** [comment]
Done, please try again

**Comment by aallnneess** [comment]
still the same issues.

`wicket:id="testClass"`

becomes:

`id="testClass" wicket`

misssst

new image:

image

right branch:

image

thanks for your support.

Maybe just not wicket compatible. since not many people use it anyway (wicket) you shouldn't invest too much time in this problem I think. And i cant help becouse i only know java.

**Comment by lexoyo** [comment]
it looks like you don't have the latest modifications
i have tested with this:
Screenshot from 2021-06-03 14-36-09

**Comment by lexoyo** [comment]
also `{ [ ] }` should work

**Comment by lexoyo** [comment]
do you need `{ [ ] }` ?

**Comment by aallnneess** [comment]
hmmmmm strange. i will try it again.



> do you need `{ [ ] }` ?

nope, was just a test

**Comment by aallnneess** [comment]
i tryed it again with 2 different ways....(github desktop app & zip) but it dont work at all...

**Comment by lexoyo** [comment]
> Here u can see that ive the newest version

show me these lines plz
https://github.com/silexlabs/Silex/pull/1105/files#diff-7f5219aa9daa4c5017f56cbaefd882df80c70e0d3d2761fb6b6d08a4b45abc64R141

**Comment by aallnneess** [comment]
dispatchers

```
/**
 * @fileoverview helpers to dispatch common actions on the store
 * TODO: 1- remove all references to the store or dispatch => every function should take ElementState[] and return the changes to be made as an ElementState[]
 * TODO: 2- move this file to a cross platform package (e.g. in src/ts/helpers/)
 */

import {
  Attr,
  Direction,
  DomDirection,
  ElementState,
  ElementType,
  Link,
  StyleObject
} from './types'
import { Constants } from '../../constants'
import { CssRule } from '../site-store/types'
import { PageState } from '../page-store/types'
import { SilexNotification } from '../components/Notification'
import { addToMobileOrDesktopStyle } from '../utils/styles'
import {
  createElements,
  deleteElements,
  getElements,
  updateElements
} from './index'
import {
  getBody,
  getChildrenRecursive,
  getElementById,
  getFirstPagedParent,
  getParent,
  getSelectedElements,
  isBody,
  noSectionContent,
  getSelectedElementsNoSectionContent
} from './filters'
import { getCreateAction } from './utils'
import { getDomElement } from './dom'
import { getSiteDocument } from '../components/SiteFrame'
import { getUi } from '../ui-store/index'
import { insertAt } from '../utils/array'
import { store } from '../store/index'

/**
 * select the body and only the body
 */
export const selectBody = (elements = getElements(), dispatch = store.dispatch) => {
  selectElements([getBody(elements)], elements, dispatch)
}

/**
 * select a set of elements
 */
export const selectElements = (selection: ElementState[], elements = getElements(), dispatch = store.dispatch) => {
  updateElements(elements
    .filter((el) => el.selected !== selection.map((e) => e.id).includes(el.id))
    .map((el) => ({
      ...el,
      selected: !el.selected,
    })),
    dispatch)
}

/**
 * move elements order in their parent's children array
 * @return the parent elements to be updated
 * FIXME: the elements hidden on mobile or desktop interfeer and they should not - see how hidden on current page is handled here
 */
export const moveElements = (selection: ElementState[], direction: DomDirection, elements = getElements(), dispatch = store.dispatch, debug = false) => {
  const { currentPageId } = getUi()
  const getIdx = (el, children) => children.findIndex((c) => c === el.id)
  const getTargetIdx = (el, parent) => {
    let idx = getIdx(el, parent.children)
    let target = null
    do {
      idx = direction === DomDirection.UP ? idx - 1 : direction === DomDirection.DOWN ? idx + 1 : direction === DomDirection.TOP ? 0 : parent.children.length - 1
      target = getElementById(parent.children[idx], elements)
    } while(!!target && target.pageNames.length && !target.pageNames.includes(currentPageId))
    return idx
  }
  const changes = selection
    .map((el) => ({
      el,
      parent: getParent(el, elements),
    }))
    .filter(({el, parent}) => {
      if (!parent) {
        console.warn('No parent, are you trying to move the root element?', {el, parent})
      }
      return !!el && !!parent
    })
    .map(({el, parent}) => ({
      el,
      parent,
      idx: getTargetIdx(el, parent),
    }))
    .sort((o1, o2) => (o2.idx - o1.idx) * (direction === DomDirection.UP || direction === DomDirection.TOP ? -1 : 1))
    .reduce((acc, {el, parent, idx}) => {
      const stored = acc.has(parent) ? acc.get(parent) : {
        children: parent.children,
        parent,
        beforeMe: 0,
        errored: false,
      }
      // how many elements have been moved before me
      const currentIdx = getIdx(el, stored.children)
      const targetIdx = idx // + (direction === DomDirection.TOP ? 0 : direction === DomDirection.BOTTOM ? 0 : 0)
      acc.set(parent, {
        parent: stored.parent,
        children: targetIdx !== currentIdx ? insertAt(stored.children.filter((c, i) => i !== currentIdx), targetIdx, el.id) : stored.children,
        errored: stored.errored || targetIdx < 0 || targetIdx >= stored.parent.children.length,
        beforeMe: stored.beforeMe + 1,
      })
      return acc
    }, new Map())
    const states = Array.from(changes.values())
      .filter((change) => !change.errored && JSON.stringify(change.children) !== JSON.stringify(change.parent.children))
      .map((change) => ({
        ...change.parent,
        children: change.children,
      })) as ElementState[]

  if (states.length) updateElements(states, dispatch)
}

/**
 * get/set the "hide on desktop" property
 * @param hide, true if the element has to be hidden on desktop
 */
export const setHideOnDesktop = (element: ElementState, hide: boolean, elements = getElements(), dispatch = store.dispatch) => {
  updateElements([{
    ...element,
    visibility: {
      ...element.visibility,
      desktop: hide,
    },
  }], dispatch)
}


/**
 * set a given style to the current selection
 * @param opt_isUndoable default is true
 * FIXME: useless method
 */
export const styleChanged = (name: string, value: string, selection: ElementState[], isMobile = getUi().mobileEditor, dispatch = store.dispatch) => {
  // build the style change object
  const newStyle = {}
  newStyle[name] = value,

  multipleStylesChanged(newStyle, selection, isMobile, dispatch)
}

/**
 * set a set of styles to the current selection
 */
export const multipleStylesChanged = (style: CssRule, selection: ElementState[], isMobile = getUi().mobileEditor, dispatch = store.dispatch) => {
  // apply the change to all elements
  updateElements(selection.map((el) => ({
    ...el,
    style: addToMobileOrDesktopStyle(isMobile, el.style, style),
  })), dispatch)
}


/**
 * set html attributes
 */
export function setAttributes(attr: Attr, elements = getElements(), dispatch = store.dispatch) {
  // apply the change to all elements
  updateElements(getSelectedElements(elements)
    .map((el) => ({
      ...el,
      attr,
    })), dispatch)
}

/**
 * set css class names
 */
export function setClassName(name: string, elements = getElements(), dispatch = store.dispatch) {
  // apply the change to all elements
  updateElements(getSelectedElements(elements)
    .map((el) => ({
      ...el,
      // note: `new Set` to make sure names are unique
      classList: [...new Set(name
        .split(' ')
        .filter((className) => className !== ''))],
    })), dispatch)
}

/**
 * create an element and add it to the stage
 * componentName the desired component type if it is a component
 * TODO: refactore add element to be able to unit test
 * @return [element, updatedParent]
 */
export async function addElement({type, parent, style, componentName} : {
  type: ElementType,
  parent: ElementState,
  style: StyleObject,
  componentName?: string,
}, dispatch = store.dispatch): Promise<[ElementState, ElementState]> {
  // create an element
  const [newElementState, updatedParentState] = await getCreateAction({
    type,
    parent,
    componentName,
    isSectionContent: false,
  })

  // add it to the current page only if it has no parent which already are in a page
  const { currentPageId } = getUi()
  const newElementStatePaged = {
    ...newElementState,
    pageNames: !!parent.pageNames.length || !!getFirstPagedParent(parent) ? [] : [currentPageId],
  }

  const element = (await (async () => {
    // if it is a section add its container element
    if (type === ElementType.SECTION) {
      if (!isBody(parent)) throw new Error('Sections can only be added to the body')
      const [contentElement, newElementStateWithContent] = await getCreateAction({
        type: ElementType.CONTAINER,
        parent: newElementStatePaged,
        componentName: null,
        isSectionContent: true,
      })
      const contentElementWithCssClasses = {
        ...contentElement,
        classList: contentElement.classList.concat([
          Constants.ELEMENT_CONTENT_CLASS_NAME,
          Constants.WEBSITE_WIDTH_CLASS_NAME,
          Constants.PREVENT_DRAGGABLE_CLASS_NAME,
        ]),
      }
      // add the elements to the store
      createElements([newElementStateWithContent, contentElementWithCssClasses], dispatch)
      return getElementById(newElementStateWithContent.id, getElements()) // here it is important to use getElements(), not store elements of before the dispatch
    } else {
      // add the elements to the store
      createElements([newElementStatePaged], dispatch)
      return getElementById(newElementStatePaged.id, getElements()) // here it is important to use getElements(), not store elements of before the dispatch
    }
  })())

  updateElements(
    // unselect all
    getSelectedElements(getElements()) // here it is important to use getElements(), not store elements of before the dispatch
    .filter((el) => el !== parent && el !== element) // will be updated bellow
    .map((el) => ({
      ...el,
      selected: false,
    }))
    // apply style + select the created element
    .concat([{
      ...element,
      selected: true,
      style: {
        mobile: {
          ...element.style.mobile,
          ...style.mobile,
        },
        desktop: {
          ...element.style.desktop,
          ...style.desktop,
        },
      },
    },
    // update the parent element
    {
      ...updatedParentState,
      selected: false,
    }]), dispatch)

  // TODO: drag to insert?
  // getStage().startDrag()

  return [getElementById(newElementStatePaged.id, getElements()), getElementById(updatedParentState.id, getElements())] // here it is important to use getElements(), not store elements of before the dispatch
}

/**
 * remove selected elements from the stage
 */
export function removeElements(elements = getSelectedElements()) {
  const body = getBody()
  const toDelete: ElementState[] = elements.filter((el: ElementState) => el !== body)
  if (toDelete.length <= 0) {
    SilexNotification.alert('Delete elements',
      'Error: Please select an element to delete.',
      () => {},
    )
  } else {
    // confirm and delete
    SilexNotification.confirm('Delete elements', `I am about to <strong>delete ${toDelete.length} element(s)</strong>, are you sure?`,
      (accept) => {
        if (accept) {
          removeElementsWithoutConfirm(toDelete)
          selectBody()
        }
      }, 'delete', 'cancel',
    )
  }
}

export function removeElementsWithoutConfirm(selection: ElementState[], elements = getElements(), dispatch = store.dispatch) {
  // get the elements and their children
  const selectionNoSectionContent = selection
    .map((el) => noSectionContent(el, elements))

  const deleted = selectionNoSectionContent
    .concat(selectionNoSectionContent
      .reduce((prev, el) => prev.concat(getChildrenRecursive(el, elements)), []))

  // update the parents to remove deleted elements from children lists
  updateElements(elements
    .filter((element: ElementState) => !deleted.includes(element)) // not in the deleted elements
    .filter((element: ElementState) => element.children.some((id) => !!deleted.find((el) => el.id === id))) // keep the parents
    .map((element: ElementState) => ({
      ...element,
      children: element.children.filter((id) => !deleted.find((el) => el.id === id)),
    })), dispatch)

  // delete the elements from the store
  deleteElements(deleted, dispatch)
}

/**
 * add the provided elements to a given page
 */
export function addToPage(selection: ElementState[], page: PageState, elements = getElements(), dispatch = store.dispatch) {
  updateElements(selection
    .map((el) => noSectionContent(el, elements))
    .map((el) => ({
      ...el,
      pageNames: el.pageNames.concat([page.id]),
    })), dispatch)
}

/**
 * remove the provided elements from a given page
 */
export function removeFromPage(selection: ElementState[], page: PageState, elements = getElements(), dispatch = store.dispatch) {
  updateElements(selection
    .map((el) => noSectionContent(el))
    .map((el) => ({
      ...el,
      pageNames: el.pageNames.filter((name) => name !== page.id),
    })), dispatch)
}

/**
 * add provided elements to all pages
 */
export function visibleOnAllPages(selection: ElementState[], dispatch = store.dispatch) {
  updateElements(selection
    .map((el) => ({
      ...el,
      pageNames: [],
    })), dispatch)
}

/**
 * add link to the provided elements
 */
export function addLink(selection: ElementState[], link: Link, dispatch = store.dispatch) {
  updateElements(selection
    .map((el) => ({
      ...el,
      link,
    })), dispatch)

}

/**
 * remove link from the provided elements
 */
export function removeLink(selection: ElementState[], dispatch = store.dispatch) {
  updateElements(selection
    .map((el) => ({
      ...el,
      link: null,
    })), dispatch)
}

/**
 * @return the opposit direction
 */
function opposit(direction: DomDirection): DomDirection {
  switch(direction) {
    case DomDirection.UP: return DomDirection.DOWN
    case DomDirection.DOWN: return DomDirection.UP
    case DomDirection.TOP: return DomDirection.BOTTOM
    case DomDirection.BOTTOM: return DomDirection.TOP
  }
}

function toDomDir(direction: Direction): DomDirection {
  switch(direction) {
    case Direction.UP: return DomDirection.UP
    case Direction.DOWN: return DomDirection.DOWN
    case Direction.LEFT: return DomDirection.TOP
    case Direction.RIGHT: return DomDirection.BOTTOM
  }
}

/**
 * Move the selected elements in the DOM
 * Move it up or down the DOM depending on the direction and the popsition property
 * A static position means that the user is moving the element compared to other static elements
 * A non-static position means that the user expect the z-order to change
 */
function move(direction: DomDirection, elements = getSelectedElementsNoSectionContent()) {
  const desktopOrMobile = getUi().mobileEditor ? 'mobile' : 'desktop'
  moveElements(elements
    .filter((el) => el.style[desktopOrMobile].position === 'static'), direction)
  moveElements(elements
    .filter((el) => el.style[desktopOrMobile].position !== 'static'), opposit(direction))
}

/**
 * useful method to shift the position of an element, keeping the "px" unit
 */
function updatePosition(options: {value: string, inc: boolean, dec: boolean, multiply: boolean, divide: boolean}): string {
  if(options.inc || options.dec) {
    const num = parseInt(options.value)
    const offset = options.multiply ? 10 : (options.divide ? 1 : 5)
    return (num + (options.inc ? offset : -offset)) + 'px'
  }
  return options.value
}

/**
 * move an element up, down, left or right. the amount is 1px, 5px or 10px depending on the key modifiers
 */
export function position(direction: Direction, { altKey, ctrlKey, shiftKey }: { altKey: boolean, ctrlKey: boolean, shiftKey: boolean }) {
  if (altKey) return
  const desktopOrMobile = getUi().mobileEditor ? 'mobile' : 'desktop'
  updateElements(getSelectedElementsNoSectionContent()
    .filter((el) => el.style[desktopOrMobile].position !== 'static')
    .map((el) => ({
      ...el,
      style: {
        ...el.style,
        [desktopOrMobile]: {
          ...el.style[desktopOrMobile],
          top: updatePosition({
            value: el.style[desktopOrMobile].top,
            inc: direction === Direction.DOWN,
            dec: direction === Direction.UP,
            multiply: ctrlKey,
            divide: shiftKey,
          }),
          left: updatePosition({
            value: el.style[desktopOrMobile].left,
            inc: direction === Direction.RIGHT,
            dec: direction === Direction.LEFT,
            multiply: ctrlKey,
            divide: shiftKey,
          }),
        },
      },
    }))
  )
  // the elements with a position set to "static" need to move in the DOM
  move(toDomDir(direction), getSelectedElementsNoSectionContent().filter((el) => el.style[desktopOrMobile].position === 'static'))
}

/**
 * Move the selected elements in the DOM
 * This will move its over or under other elements if the z-index CSS
 * properties are not set
 */
export function moveUp() {
  move(DomDirection.UP)
}

/**
 * Move the selected elements in the DOM
 * This will move its over or under other elements if the z-index CSS
 * properties are not set
 */
export function moveDown() {
  move(DomDirection.DOWN)
}

/**
 * Move the selected elements in the DOM
 * This will move its over or under other elements if the z-index CSS
 * properties are not set
 */
export function moveToTop() {
  move(DomDirection.TOP)
}

/**
 * Move the selected elements in the DOM
 * This will move its over or under other elements if the z-index CSS
 * properties are not set
 */
export function moveToBottom() {
  move(DomDirection.BOTTOM)
}

/**
 * set/get the image URL of an image element
 */
export function setImageUrl(image: ElementState, url: string) {
  updateElements([{
    ...image,
    // innerHtml: `<div class="${Constants.ELEMENT_CONTENT_CLASS_NAME}" ><img src="${url}" /></div>`
    // innerHtml: `<img src="${url}" class="${Constants.ELEMENT_CONTENT_CLASS_NAME}" />`
    innerHtml: `<img src="${url}" />`
  }])
  // get the image tag
  const img: HTMLImageElement = getDomElement(getSiteDocument(), image)
  .querySelector('img')
  // when loaded, update the element size
  img.addEventListener('load', () => {
    // get the up to date image data
    const updated = getElementById(image.id)
    updateElements([{
      ...updated,
      style: {
        ...updated.style,
        desktop: {
          ...updated.style.desktop,
          width: img.naturalWidth + 'px',
          height: img.naturalHeight + 'px',
        },
      },
    }])
  })
}

```

**Comment by aallnneess** [comment]
so, i waited a few hours, re-downloaded and new image .... now it works ?!
No further errors so far, thanks

**Comment by aallnneess** [comment]
do you need the project data, too ?

**Comment by lexoyo** [comment]
why? do you still have a bug?

**Comment by aallnneess** [comment]
oh, sry, wrong Issues, i mean https://github.com/silexlabs/Silex/issues/1118

**Comment by lexoyo** [comment]
Any news @aallnneess ?
How is it working so far?

**Comment by aallnneess** [comment]
hey, it works without errors so far. From next week I will work more intensively with Silex again and can continue testing.

**Comment by lexoyo** [comment]
hello
i changed the regexp a little, one last time
let me know if you can test
i will release this feature soon

**Comment by aallnneess** [comment]
hey, i had problems with wicket so i cant work with silex so much, but know it works well. i dont have any problems ! but i will test latest update

**Pull request merged**
